"""empty message

Revision ID: 033903065df1
Revises: e72c85cb43ea
Create Date: 2016-11-08 17:25:25.111228

"""

# revision identifiers, used by Alembic.
revision = '033903065df1'
down_revision = 'e72c85cb43ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('order_item', sa.Column('price', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'price')
    op.alter_column('invoice', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
