"""empty message

Revision ID: 1ffd1d0c540e
Revises: 4b89664c7c06
Create Date: 2016-11-08 23:28:18.985002

"""

# revision identifiers, used by Alembic.
revision = '1ffd1d0c540e'
down_revision = '4b89664c7c06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
