"""empty message

Revision ID: 3bd8484e76cc
Revises: 033903065df1
Create Date: 2016-11-08 17:33:43.557763

"""

# revision identifiers, used by Alembic.
revision = '3bd8484e76cc'
down_revision = '033903065df1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean()))
    ### end Alembic commands ###

    op.execute('UPDATE "user" SET is_admin = false')

    op.alter_column("user", "is_admin", nullable=True)




def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    ### end Alembic commands ###
