"""empty message

Revision ID: 4b89664c7c06
Revises: e026a03b3bf2
Create Date: 2016-11-08 23:27:55.566073

"""

# revision identifiers, used by Alembic.
revision = '4b89664c7c06'
down_revision = 'e026a03b3bf2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
