"""empty message

Revision ID: 5fa9c75f922b
Revises: 1ffd1d0c540e
Create Date: 2016-11-08 23:32:45.786915

"""

# revision identifiers, used by Alembic.
revision = '5fa9c75f922b'
down_revision = '1ffd1d0c540e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
