"""empty message

Revision ID: e026a03b3bf2
Revises: 3bd8484e76cc
Create Date: 2016-11-08 23:24:21.831464

"""

# revision identifiers, used by Alembic.
revision = 'e026a03b3bf2'
down_revision = '3bd8484e76cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
