"""empty message

Revision ID: e72c85cb43ea
Revises: 16cdefea703a
Create Date: 2016-11-04 12:56:09.231789

"""

# revision identifiers, used by Alembic.
revision = 'e72c85cb43ea'
down_revision = '16cdefea703a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('stripe_id', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'stripe_id')
    ### end Alembic commands ###
